name: Update Dependencies
on:
  schedule:
    - cron: '0 10 * * 1'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install pip-compile-multi
      - name: Update dependencies
        run: |
          pip-compile-multi
      - name: Create commits
        run: |
          git config user.name 'pip-compile-multi'
          git config user.email 'pip-compile-multi@users.noreply.github.com'
          tail -n+3 HISTORY.rst > HISTORY.rst.tail
          mv HISTORY.rst HISTORY.rst.tmp
          head -n2 HISTORY.rst.tmp > HISTORY.rst
          rm HISTORY.rst.tmp
          date '+UNRELEASED (%Y-%m-%d)' >> HISTORY.rst
          echo >> HISTORY.rst << EOF
          -----------------------

          * Update dependencies
          EOF
          cat HISTORY.rst.tail >> HISTORY.rst
          rm HISTORY.rst.tail
          git commit -am "Update dependencies"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
            token: ${{ secrets.PAT }}
            title: Update dependencies
            body: |
              Auto-generated by [pip-compile-multi](github.com/peterdemin/pip-compile-multi)
            branch: update-dependencies-
            branch-suffix: timestamp
